services:
  nagios:
    image: redbranch/nagios-container-image:20250523001
    container_name: nagios
    ports:
      - 3009:80
    volumes:
      - ./conf/nagios/conf.d:/etc/nagios/conf.d
      - ./data/var_spool/nagiosgraph:/var/spool/nagiosgraph
      - ./data/var_spool/nagios/checkresults:/var/spool/nagios/checkresults
      - ./data/var_lib_nagios/rw:/var/lib/nagios4/rw
    environment:
      - SLACK_HOSTNAME=${SLACK_HOSTNAME}
      - SLACK_BOTUSERNAME=${SLACK_BOTUSERNAME}
      - MONITORING_URL=${MONITORING_URL}
      - SLACK_CHANNEL=${SLACK_CHANNEL}
      - WEBHOOK_ADDRESS=${WEBHOOK_ADDRESS}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_STARTTLS=${SMTP_STARTTLS}
