version: '3'

dotenv: ['.env']

tasks:

  up:
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f docker-compose.yml
    cmds:
      - docker-compose up -d

  down:
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f docker-compose.yml
    cmds:
      - docker-compose down

  restart:
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f docker-compose.yml
    cmds:
      - docker-compose down
      - docker-compose up -d

  exec:
    cmds:
      - docker exec -it nagios /bin/bash 

  build:
    dir: '{{.USER_WORKING_DIR}}'
    desc: "Build the container image"
    env:
      NAGIOSGRAPH_VERSION: 1.5.2
      VERSION: 20250523001
    cmds: 
      - |
        if [ ! -f tmp/nagiosgraph-$NAGIOSGRAPH_VERSION.tar.gz ]; then
          wget -O tmp/nagiosgraph-$NAGIOSGRAPH_VERSION.tar.gz http://downloads.sourceforge.net/project/nagiosgraph/nagiosgraph/$NAGIOSGRAPH_VERSION/nagiosgraph-$NAGIOSGRAPH_VERSION.tar.gz
        fi
      - docker build -t redbranch/nagios-container-image:$VERSION -t redbranch/nagios-container-image:latest .
  
  push:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - echo "$DOCKER_PASSWORD" | docker login -u redbranch --password-stdin
      - docker push redbranch/nagios-container-image
