# This workflow is used by the Release Engineering Team
name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAGIOSGRAPH_VERSION: 1.5.2 
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Read version
        id: read_version
        run: echo "VERSION=$(cat VERSION.txt)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          mkdir tmp
          wget -O tmp/nagiosgraph-$NAGIOSGRAPH_VERSION.tar.gz http://downloads.sourceforge.net/project/nagiosgraph/nagiosgraph/$NAGIOSGRAPH_VERSION/nagiosgraph-$NAGIOSGRAPH_VERSION.tar.gz
          docker build -t redbranch/nagios-container-image:${{ env.VERSION }} -t redbranch/nagios-container-image:latest .
          docker push redbranch/nagios-container-image:${{ env.VERSION }}
