# This workflow is used by the Release Engineering Team
name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Read version from VERSION.txt
      - name: Read version
        id: read_version
        run: echo "VERSION=$(cat VERSION.txt)" >> $GITHUB_ENV

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t redbranch/nagios-container-image:${{ env.VERSION }} -t redbranch/nagios-container-image:latest .
          docker push redbranch/nagios-container-image:${{ env.VERSION }}

